name: comment_flutter_template
description: ""

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.4.3+1
  google_fonts: ^6.2.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  rename:

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - assets/
  - assets/images/
  - assets/icons/
  - assets/fonts/
  - assets/json/
  - assets/svg/
